melon_details = {'Honeydew': {
                    'price': 0.99, 
                    'seedless': True,
                    'flesh': None,
                    'weight': None,
                    'rind': None}, 
                'Crenshaw': {
                    'price': 2.0, 
                    'seedless': False,
                    'flesh': None,
                    'weight': None,
                    'rind': None}, 
                'Crane': {
                    'price': 2.5, 
                    'seedless': False,
                    'flesh': None,
                    'weight': None,
                    'rind': None}, 
                'Casaba': {
                    'price': 2.5, 
                    'seedless': False,
                    'flesh': None,
                    'weight': None,
                    'rind': None}, 
                'Cantaloupe': {
                    'price': 0.99, 
                    'seedless': False,
                    'flesh': None,
                    'weight': None,
                    'rind': None}}
